insert into Activity (name) values ('образование');
insert into Activity (name) values ('здравоохранение');
insert into Activity (name) values ('наука');
insert into Activity (name) values ('культура');
insert into Activity (name) values ('торговля');
insert into Activity (name) values ('IT');
insert into Activity (name) values ('собственный бизнес');
insert into Activity (name) values ('транспорт');
insert into Activity (name) values ('производство');
insert into Activity (name) values ('высший менеджмент, управление');
insert into Activity (name) values ('юриспруденция');
insert into Activity (name) values ('административный персонал');
insert into Activity (name) values ('архитектура и проектирование');
insert into Activity (name) values ('банки, инвестиции, лизинг');
insert into Activity (name) values ('бухучет и аудит');
insert into Activity (name) values ('ветеринария');
insert into Activity (name) values ('вооруженные силы');
insert into Activity (name) values ('государственная служба');
insert into Activity (name) values ('гостиничное дело');
insert into Activity (name) values ('добыча сырья');
insert into Activity (name) values ('органы власти и правопорядка');
insert into Activity (name) values ('издательское дело');
insert into Activity (name) values ('индустрия развлечений');
insert into Activity (name) values ('консалтинг');
insert into Activity (name) values ('маркетинг, PR');
insert into Activity (name) values ('религиозные организации');
insert into Activity (name) values ('сельское хозяйство');
insert into Activity (name) values ('спорт');
insert into Activity (name) values ('средства массовой информации');
insert into Activity (name) values ('страхование');
insert into Activity (name) values ('строительство, недвижимость');
insert into Activity (name) values ('судебные органы');
insert into Activity (name) values ('HR, управление персоналом');
insert into Activity (name) values ('студент');
insert into Activity (name) values ('не работаю');
insert into Activity (name) values ('другое');